apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persisent-volume-claim
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
